In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
from google.colab import files
uploaded = files.upload()

Saving data_train.csv to data_train.csv


In [0]:
import io
data = pd.read_csv(io.BytesIO(uploaded['data_train.csv']))

In [101]:
data.head()

Fully Paid  Current Loan Amount  ...  vacation  wedding
0           1             445412.0  ...         0        0
1           1           99999999.0  ...         0        0
2           1             347666.0  ...         0        0
3           0             206602.0  ...         0        0
4           1             217646.0  ...         0        0

[5 rows x 30 columns]

In [102]:
data.info

<bound method DataFrame.info of        Fully Paid  Current Loan Amount  ...  vacation  wedding
0               1             445412.0  ...         0        0
1               1           99999999.0  ...         0        0
2               1             347666.0  ...         0        0
3               0             206602.0  ...         0        0
4               1             217646.0  ...         0        0
...           ...                  ...  ...       ...      ...
80678           1             147070.0  ...         0        0
80679           1           99999999.0  ...         0        0
80680           1             103136.0  ...         0        0
80681           1             530332.0  ...         0        0
80682           1           99999999.0  ...         0        0

[80683 rows x 30 columns]>

## **Data Splitting**

In [0]:
X = data.drop(columns='Fully Paid')
y = data['Fully Paid']

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [106]:
print(X_train)
print(X_test)

       Current Loan Amount  Credit Score  ...  vacation  wedding
11884             387530.0         693.0  ...         0        0
50248           99999999.0         718.0  ...         0        0
36468             769692.0         656.0  ...         0        0
47855           99999999.0         728.0  ...         0        0
38612             394108.0         726.0  ...         0        0
...                    ...           ...  ...       ...      ...
49464              65076.0         727.0  ...         0        0
36275             336710.0         744.0  ...         0        0
29345             468446.0         683.0  ...         0        0
32497             400356.0         669.0  ...         0        0
9374              435600.0        7010.0  ...         0        0

[56478 rows x 29 columns]
       Current Loan Amount  Credit Score  ...  vacation  wedding
7429              183678.0         732.0  ...         0        0
45029             511390.0         669.0  ...         0        

## **Model 1: Logistic Regression**

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
model = LogisticRegression()

In [109]:
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
pred = model.predict(X_test)

In [0]:
# Metrics:

from sklearn.metrics import classification_report, confusion_matrix

In [112]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.91      0.26      0.41      5098
           1       0.83      0.99      0.91     19107

    accuracy                           0.84     24205
   macro avg       0.87      0.63      0.66     24205
weighted avg       0.85      0.84      0.80     24205



In [113]:
print(confusion_matrix(y_test, pred))

[[ 1347  3751]
 [  138 18969]]


## **Model 1: Grid Search (Logistic Regression)**

In [0]:
from sklearn.model_selection import GridSearchCV

In [0]:
param_grid_log_reg = {'C':np.arange(1, 100, 1)}

In [0]:
grid_log_reg = GridSearchCV(LogisticRegression(), param_grid=param_grid_log_reg, refit=True)

In [117]:
grid_log_reg.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


GridSearchCV(cv=None, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': array([ 1,  2,  3,  4,  5,  6,  7,  8...12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74,

In [118]:
grid_log_reg.best_params_

{'C': 31}

In [0]:
pred_grid_log_reg = grid_log_reg.predict(X_test)

In [120]:
print(classification_report(y_test, pred_grid_log_reg))

              precision    recall  f1-score   support

           0       0.91      0.26      0.41      5098
           1       0.83      0.99      0.91     19107

    accuracy                           0.84     24205
   macro avg       0.87      0.63      0.66     24205
weighted avg       0.85      0.84      0.80     24205



In [121]:
print(confusion_matrix(y_test, pred_grid_log_reg))

[[ 1347  3751]
 [  138 18969]]


## **Model 2: Random Forest**

In [0]:
from sklearn.ensemble import RandomForestClassifier

In [0]:
model2 = RandomForestClassifier()

In [124]:
model2.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
pred_random_forest = model2.predict(X_test)

In [126]:
# Metrics:

print(classification_report(y_test, pred_random_forest))
print(confusion_matrix(y_test, pred_random_forest))

              precision    recall  f1-score   support

           0       0.96      0.27      0.43      5098
           1       0.84      1.00      0.91     19107

    accuracy                           0.84     24205
   macro avg       0.90      0.64      0.67     24205
weighted avg       0.86      0.84      0.81     24205

[[ 1395  3703]
 [   62 19045]]


## **Model 3: SVM**

In [0]:
from sklearn.svm import SVC

In [0]:
model3 = SVC()

In [129]:
model3.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
pred_svm = model3.predict(X_test)

In [131]:
# Metrics:

print(classification_report(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      5098
           1       0.79      1.00      0.88     19107

    accuracy                           0.79     24205
   macro avg       0.39      0.50      0.44     24205
weighted avg       0.62      0.79      0.70     24205

[[    0  5098]
 [    0 19107]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## **Model 4: Neural Network**

In [0]:
import tensorflow as tf

In [140]:
model4 = tf.keras.models.Sequential()

model4.add(tf.keras.layers.Flatten(input_shape=(29, )))
model4.add(tf.keras.layers.Dense(32, activation='relu'))
model4.add(tf.keras.layers.Dense(64, activation='relu'))
model4.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model4.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_9 (Flatten)          (None, 29)                0         
_________________________________________________________________
dense_32 (Dense)             (None, 32)                960       
_________________________________________________________________
dense_33 (Dense)             (None, 64)                2112      
_________________________________________________________________
dense_34 (Dense)             (None, 1)                 65        
Total params: 3,137
Trainable params: 3,137
Non-trainable params: 0
_________________________________________________________________


In [0]:
model4.compile(loss='binary_crossentropy',
               optimizer='adam',
               metrics='accuracy')

In [0]:
call = tf.keras.callbacks.EarlyStopping(monitor='loss',
                                        patience=10)

In [143]:
model4.fit(X_train, y_train, epochs=100, batch_size=32, callbacks=call)

Epoch 1/100
1765/1765 [==============================] - 6s 3ms/step - loss: 2303.5530 - accuracy: 0.7156
Epoch 2/100
1765/1765 [==============================] - 6s 3ms/step - loss: 1876.0953 - accuracy: 0.7290
Epoch 3/100
1765/1765 [==============================] - 6s 3ms/step - loss: 1221.2205 - accuracy: 0.7336
Epoch 4/100
1765/1765 [==============================] - 6s 3ms/step - loss: 2352.3501 - accuracy: 0.7292
Epoch 5/100
1765/1765 [==============================] - 6s 3ms/step - loss: 547.1277 - accuracy: 0.7293
Epoch 6/100
1765/1765 [==============================] - 6s 3ms/step - loss: 498.7220 - accuracy: 0.7298
Epoch 7/100
1765/1765 [==============================] - 6s 3ms/step - loss: 434.2332 - accuracy: 0.7279
Epoch 8/100
1765/1765 [==============================] - 6s 4ms/step - loss: 426.4268 - accuracy: 0.7115
Epoch 9/100
1765/1765 [==============================] - 7s 4ms/step - loss: 405.2371 - accuracy: 0.7784
Epoch 10/100
1765/1765 [===========================

In [144]:
# Metrics:

test_loss, test_acc = model4.evaluate(X_test, y_test)

757/757 [==============================] - 2s 3ms/step - loss: 0.4857 - accuracy: 0.7894


In [146]:
print('Loss in Test Set: ',test_loss)
print('Accuracy in Test Set: ',test_acc)

Loss in Test Set:  0.48565539717674255
Accuracy in Test Set:  0.7893823385238647


## **Winner Model: Logistic Regression**